### PR TITLE
GCI: Integrate Google sign in using Firebase

### PR DESCRIPTION
**Pull request by HITGIF**
For the [task](https://codein.withgoogle.com/dashboard/task-instances/5798542650114048/)

### CODE REVIEW

**Comment by SachinRammoorthy** [comment]
@HITGIF I cannot help but notice that your code is quite similar to mine in #19 . Even some of the classes you specified in index.html really do not exist and are from my code. Furthermore, the `google-signin-client_id` is the same too! In the spirit of the competition, would you mind submitting your own code please?

**Comment by yashovardhanagrawal** [comment]
@garg-anuj @m-murad please look into this matter

**Comment by HITGIF** [comment]
@SachinRammoorthy Thank you for pointing it out, I totally agree with you and I'm sorry that this happened.

As I'm completely new to Javascript and frontend, I start my code following the steps in the official Firebase document, which I'm sure you did so, leading to we having the similar code structure here. 

Then I had some difficulty of making it work, so I looked into your code and added some into my index.html  (including that `google-signin-client_id`) to see where I got wrong and in which way it would work. Finally I found that it was the API key problem and forgot about the changes in the previous file, and created the PR with your code in it (that I used for testing), which I'm sincerely sorry about. I wasn't intended to plagiarize yet as you have pointed it out, I realized the lack of originality and it seems it's what I have done.

I'll close this PR now and figure out another way of implementation. Sorry for what's happening here ;)

**Comment by HITGIF** [comment]
New PR here #21 :)

**Comment by SachinRammoorthy** [comment]
Thanks @HITGIF . Appreciate that.

**Pull request closed without merging**
